import test from 'node:test';
import assert from 'node:assert/strict';
import { ApiError, createProfileApi, fromBackendProfile, toBackendProfile } from '../src/profile-api.js';
const profile = { birth_date: '2002-05-12', region: 'gyeonggi-yongin', residence_start_date: '2026-05-01', education: 'graduated', employment_status: 'unemployed', marital_status: 'single', household_size: 3, personal_income: null, household_income: null, employment_type: null };
function fakeFetch(queue) { const calls = []; return { calls, fetch: async (url, options) => { calls.push({ url, options }); const next = queue.shift(); if (next instanceof Error) throw next; const body = next.body ?? ''; return new Response(body || null, { status: next.status ?? 200, headers: body ? { 'Content-Type': 'application/json' } : undefined }); } }; }
function storage() { const m = new Map(); return { getItem: key => m.get(key) ?? null, setItem: (key, value) => m.set(key, value), removeItem: key => m.delete(key) }; }
test('maps supported draft values to BE core/history/consent contract', () => { const result = toBackendProfile(profile, { receivedPolicyIds: ['P1'], similarProgramParticipation2y: false, incomeBasis: 'household_incl_parents', householdIncomeRatioMedian: 120 }); assert.deepEqual(result.core, { birth_date: '2002-05-12', region_code: '41465', residence_start_date: '2026-05-01', education: 'university_graduated', employment_status: 'job_seeking', employment_start_date: null, marital_status: 'single', household_size: 3, income_basis: 'household_incl_parents', household_income_ratio_median: 120 }); assert.deepEqual(result.history, { received_policy_ids: ['P1'], similar_program_participation_2y: false }); assert.deepEqual(result.consent, { privacy_agreed_at: null }); });
test('does not silently discard unsupported income or employment fields', () => { assert.throws(() => toBackendProfile({ ...profile, household_income: 3000000 }), e => e instanceof ApiError && e.code === 'PROFILE_MAPPING_REQUIRED'); });
test('rejects unsupported enum and region values instead of converting them to null', () => { for (const draft of [{ ...profile, education: 'on-leave' }, { ...profile, employment_status: 'other' }, { ...profile, marital_status: 'other' }, { ...profile, region: 'unknown' }]) assert.throws(() => toBackendProfile(draft), e => e instanceof ApiError && e.code === 'PROFILE_MAPPING_REQUIRED'); });
test('maps a BE profile back to the existing form draft shape', () => { assert.deepEqual(fromBackendProfile({ core: { birth_date: '2002-05-12', region_code: '41465', education: 'university_enrolled', employment_status: 'founder', marital_status: 'married', household_size: 2 }, history: { received_policy_ids: ['P1'] } }), { birth_date: '2002-05-12', region: 'gyeonggi-yongin', residence_start_date: '', education: 'enrolled', employment_status: 'self-employed', marital_status: 'married', household_size: 2, personal_income: null, household_income: null, employment_type: null, policy_history: 'yes' }); });
test('creates session with JSON and sends session header on subsequent requests', async () => { const f = fakeFetch([{ status: 201, body: JSON.stringify({ session_id: '123e4567-e89b-42d3-a456-426614174000' }) }, { status: 204 }]); const api = createProfileApi({ baseUrl: 'https://be.test/', fetchImpl: f.fetch, storage: storage() }); const id = await api.create({ core: {} }); await api.put({ core: {} }); assert.equal(id, api.sessionId); assert.equal(f.calls[0].url, 'https://be.test/v1/sessions'); assert.equal(f.calls[1].options.headers.get('X-Session-Id'), id); assert.equal(f.calls[1].options.headers.get('Content-Type'), 'application/json'); });
test('gets profile, creates on upsert without session, and removes session after delete', async () => { const store = storage(); const f = fakeFetch([{ status: 201, body: JSON.stringify({ session_id: '123e4567-e89b-42d3-a456-426614174000' }) }, { status: 200, body: JSON.stringify({ session_id: '123e4567-e89b-42d3-a456-426614174000', profile: { core: { birth_date: '2002-05-12' } } }) }, { status: 204 }]); const api = createProfileApi({ fetchImpl: f.fetch, storage: store }); await api.upsert({ core: {} }); assert.deepEqual(await api.get(), { core: { birth_date: '2002-05-12' } }); assert.equal(await api.remove(), true); assert.equal(api.sessionId, null); });
test('clears expired session after 404 and does not hide other errors', async () => { const store = storage(); const f = fakeFetch([{ status: 404, body: JSON.stringify({ detail: '없음' }) }]); const api = createProfileApi({ fetchImpl: f.fetch, storage: store }); store.setItem('ypc.session-id.v1', '123e4567-e89b-42d3-a456-426614174000'); await assert.rejects(api.get(), e => e.status === 404); assert.equal(api.sessionId, null); });
test('normalizes network, invalid JSON response and HTTP errors', async () => { const networkStore = storage(); networkStore.setItem('ypc.session-id.v1', '123e4567-e89b-42d3-a456-426614174000'); const network = createProfileApi({ fetchImpl: async () => { throw new Error('offline'); }, storage: networkStore }); await assert.rejects(network.get(), e => e.code === 'NETWORK_ERROR'); const invalid = createProfileApi({ fetchImpl: async () => new Response('{broken', { status: 200 }), storage: storage() }); await assert.rejects(invalid.create(), e => e.code === 'INVALID_RESPONSE'); const http = createProfileApi({ fetchImpl: async () => new Response(JSON.stringify({ detail: 'bad' }), { status: 422 }), storage: storage() }); await assert.rejects(http.create(), e => e.status === 422 && e.detail === 'bad'); });
test('upsert uses PUT for an existing session and create uses no body when empty', async () => { const store = storage(); store.setItem('ypc.session-id.v1', '123e4567-e89b-42d3-a456-426614174000'); const f = fakeFetch([{ status: 204 }]); const api = createProfileApi({ fetchImpl: f.fetch, storage: store }); await api.upsert({ core: {} }); assert.equal(f.calls[0].url, '/v1/sessions/123e4567-e89b-42d3-a456-426614174000'); });
